version: '2.1'

networks:
  influxdb:

services:
  influxdb:
    image: "influxdb:1.6.4-alpine"
    volumes:
    - "./data/influx:/var/lib/influxdb"
    - "./configs/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    networks:
    - influxdb
    environment:
      - "INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf"

  telegraf:
    image: "telegraf:1.5.1-alpine"
    networks:
    - influxdb
    volumes:
    - "./data/influx:/var/lib/telegraf"
    - "./configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    - "/var/run/utmp:/var/run/utmp:ro" # This is workaround https://github.com/influxdata/telegraf/issues/3339

  kapacitor:
    image: "kapacitor:1.5.1-alpine"
    networks:
      - influxdb
    volumes:
    - "./data/kapacitor:/var/lib/kapacitor"
    - "./configs/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro"
    environment:
      - "KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086"

  chronograf:
    image: "chronograf:1.6.2-alpine"
    networks:
      - influxdb
    ports:
      - 8888:8888
    volumes:
      - "./data/chronograf:/var/lib/chronograf"
      - "./configs/chronograf/canned:/usr/share/chronograf/canned"
    environment:
      - "BOLT_PATH=/var/lib/chronograf/chronograf-v1.db"
      - "CANNED_PATH=/usr/share/chronograf/canned"
      - "INFLUXDB_URL=http://influxdb:8086"
    command: "chronograf"

  exdata:
    build: .
    networks:
      - influxdb
    ports:
      - 8181:8181
